language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: muIw8wtY8Jk+y6nxWQQmwvc4yjpXo4Btx90dyicW4pAifnybVxAlLV/eqeBor4w60C27ACtzTlZpTBJNqbipoDLgJdyqTlwl7G7YHFJb155SntQPLDJSlDtjpEPEYqJlK27SeV5UjFPjmfUf6I39CqkpxDKjoRYexKsPFYki2AjQggbLof3qyAn/YHdTgWRJe5byFaYAhu6v1pC7B0Z20OQ013EFplvZxrFacrBAhYdbwxTtCIJ2mBTl3+QuoV1swY3Oa5ehRTE3W4mmUWo7VYntOGxevwVHeaDx2nFeR7Q6P9WKNW89CZIHnO+jxZyMsqjEcXUGJLgzSOU5GdrmBkchWmLR2HC59lCbvRdu7xVxDlLQjbHhXpX2hgFYLVNWXxTUPfsZw+Rg0P1JMpafppYwL6PRVK28tyXZX8CeVLIWk2JYeTfVdf3cFxfBCIKP0zMqQA0ySNcMsRhpolmRI6O0F+/pwknVT1g9L0d6Vty5CqhjHGgBiGL83P6mBo/ycrYkC6ccbV1y5+DHWii/ICvlsB8n2LMpI6y9gywNDbkIOjWHKeu7QQTKrKks0jiG17OkN30JXNhGsHJyixH1qr1w9iu1ZLvE36RmeQKKnSSvFZUBz/7c+6il65IiaZQB/qGTWHkzXGSIc3+4Mp0O8aHD/uEzPUd0pG8zeORr74U=
  app: kv-travis-git-heroku
  on:
    repo: Volkir87/Travis-GitHub-Heroku
